### PR TITLE
Magento 2.4 and php7.4 compatibility

### PR DESCRIPTION
**Pull request by aboritskiy**
things are moving forward and we need to keep up with them, here is a little PR to bump dependencies versions.

### CODE REVIEW

**Review by girishanand — APPROVED** [review]
Many thanks

**Comment by aboritskiy** [comment]
puh, looks like build has failed again due to missing composer auth, that looks weird.

**Comment by aboritskiy** [comment]
I don't see why php 7.3 and 7.4 build have failed, while 7.1 has succeeded. 
as if composer keys that you are using are not allowed to access Magento 2.4 version (which could be if 2.4.1 is attempted to be installed) alternative is: someone changed travis env vars right in the moment between php 7.2 build execution and 7.3 build build execution.

@girishanand do you have any further hints on that?

**Comment by aboritskiy** [comment]
also I've jsut double-checked: on my local machine running Ubuntu with php7.4 - it installs correctly by simply running `composer install` but my local machine is of course authenticated.

I'm not a big travis specialist, we mostly use bitbucket-pipelines, but it might be better to use `COMPOSER_AUTH` env variable to authenticate composer from inside the travis container? https://getcomposer.org/doc/03-cli.md#composer-auth

**Comment by girishanand** [comment]
> 
> 
> I don't see why php 7.3 and 7.4 builds have failed, while 7.2 has succeeded.
> as if composer keys that you are using are not allowed to access Magento 2.4 version (which could be if 2.4.1 is attempted to be installed) alternative is: someone changed travis env vars right in the moment between php 7.2 build execution and 7.3 build build execution.
> 
> @girishanand do you have any further hints on that?
> 
> UPDATE: possible suggestion here, for php7.2 composer installs completely from cache cause it is warmed up in the pipeline, but php7.3 and php7.4 require different packages and cause of that pipeline fails, cause composer can't pull new things, but luckily works with something that is in the cache.

Hello @aboritskiy ,
Not sure why it failed, it might be the case where the auth.json is not looked in the current working dir.
Possible solution could be to add the credentials in composer config
composer config http-basic.repo.magento.com <public_key> <private_key>

**Comment by aboritskiy** [comment]
Hi @girishanand, I've changed the travis config to try what you are suggesting, but I don't see how to trigger another build here, cause it seems it wasn't triggered automatically.

Also could you please validate that `${MAGENTO_USERNAME} ${MAGENTO_PASSWORD}` are actually configured in travis?

**Comment by aboritskiy** [comment]
Hi @girishanand ,

I've changed the .travis configuration to validate if ENV variables are set, apparently they are not set, see:

```
$ echo "Using ${MAGENTO_USERNAME} for repo.magento.com auth"
Using  for repo.magento.com auth
```

I also configured travis on my fork and there I specified both variables, that is how it should look like:

```
0.00s$ echo "Using ${MAGENTO_USERNAME} for repo.magento.com auth"
Using [secure] for repo.magento.com auth
```

See also my builds in Sitewards Travis: https://travis-ci.org/github/sitewards/magento2-module-gift-sales-rule/builds/733932981

Now I'm convinced that problem is with travis configuration, seems like you are missing env variables there, could you please double check them?

**Comment by girishanand** [comment]
> Hi @girishanand ,
> 
> I've changed the .travis configuration to validate if ENV variables are set, apparently they are not set, see:
> 
> ```
> $ echo "Using ${MAGENTO_USERNAME} for repo.magento.com auth"
> Using  for repo.magento.com auth
> ```
> 
> I also configured travis on my fork and there I specified both variables, that is how it should look like:
> 
> ```
> 0.00s$ echo "Using ${MAGENTO_USERNAME} for repo.magento.com auth"
> Using [secure] for repo.magento.com auth
> ```
> 
> See also my builds in Sitewards Travis: https://travis-ci.org/github/sitewards/magento2-module-gift-sales-rule/builds/733932981
> 
> Now I'm convinced that problem is with travis configuration, seems like you are missing env variables there, could you please double check them?

Thanks for checking with different approach.
I am not the author for the repo so not cannot check the configuration of travis.

@maximequeneau can you please help here as what could be the issue ?

Thankyou

**Comment by aboritskiy** [comment]
@maximequeneau  would love some support from you to get this merged - please see details above.

**Comment by maximequeneau** [comment]
Variable ${MAGENTO_USERNAME} and ${MAGENTO_PASSWORD} are secure environment variables. This variables are not available for external pull request (https://docs.travis-ci.com/user/pull-requests/).

I create and merge pull request without update travis configuration (https://github.com/Smile-SA/magento2-module-gift-sales-rule/pull/35).
Now, you can use module in Magento 2.4.x.

I will try to update the travis configuration for php 7.3 and 7.4.

**Pull request closed without merging**
