### PR TITLE
Test for magento framework dependency for M2.4 version

### PR DESCRIPTION
**Pull request by girishanand**

### CODE REVIEW

**Comment by aboritskiy** [comment]
what about compatibility to Magento 2.3? Should it be simply dropped? There are still shops that would run on Magento 2.3.x for a bit of time, should they not receive upgrades? 

Also you commit messages are contradicting each other, commit messages say "remove version" in fact you are changing it.

**Comment by girishanand** [comment]
> 
> 
> what about compatibility to Magento 2.3? Should it be simply dropped? There are still shops that would run on Magento 2.3.x for a bit of time, should they not receive upgrades?
> 
> Also you commit messages are contradicting each other, commit messages say "remove version" in fact you are changing it.

Hello This was a test to check if that is the cause its falling for the M2.4 version I will remove the PR. 
Intention is it should work for current and higher version but for some reason its failing to install.

**Comment by girishanand** [comment]
No need as of now . This was for testing

**Comment by aboritskiy** [comment]
> Intention is it should work for current and higher version but for some reason its failing to install.

it has failed cause magento 2.4 is not compatible with php `7.2` and tests were executed with `7.1` and `7.2`

I've just added another pull-request approaching it a bit different, let's see if it passes the build

**Comment by aboritskiy** [comment]
see https://github.com/Smile-SA/magento2-module-gift-sales-rule/pull/33

**Pull request closed without merging**
